repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff-format
        files: ^src/
        exclude: ^src/fluidgym/simulation/pict/.*
      - id: ruff-check
        files: ^src/
        exclude: ^src/fluidgym/simulation/pict/.*
        args: [ --fix ]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^src/
        exclude: >                     
          (^src/fluidgym/simulation/pict/.*)|
        additional_dependencies:
          - types-setuptools
          - scipy-stubs
          - types-seaborn
          - pandas-stubs
